Mobiles = ["Mobiles","Tablets"]
Laptops = ["Laptops"]
Desktop = ["Desktop"]



# DARAZ CATEGORIES
'Desktops'
'Cameras'
'Printers'
'Mobile Accessories'
'Audio'
'Wearable'
'Console Accessories'
'Camera Accessories'
'Computer Accessories'
'Storage'
'Computer Components'
'Network Components'
'Printers'
'Televisions'
'TV Accessories'
'Audio & Video Devices'
'Large Appliances'
'Small Kitchen Appliances'
'Cooling & Heating'
'Vacuums & Floor Care'
'Iron & Garment Care'
'Bath & Body'
'Beauty Tools'
'Fragrances'
'Hair Care'
'Makeup'
"Men's Care"
'Personal Care'
'Skin Care'
'Food Supplements'
'Medical Supplies'
'Baby Gear'
'Baby Personal Care'
'Clothing & Accessories'
'Diapering & Potty'
'Feeding'
'Nursery'
'Baby & Toddler Toys'
'Toys & Games'
'Remote Control & Vehicles'
'Sports & Outdoor Play'
'Beverages'
'Breakfast, Choco & Snacks'
'Food Staples'
'Cooking Ingredients'
'Laundry & Household'
'Wines, Beers & Spirits'
'Pet Supplies'
'Bath'
'Bedding'
'Decor'
'Furniture'
'Kitchen & Dining'
'Lighting'
'Laundry & Cleaning'
'Tools, DIY & Outdoor'
'Stationery & Craft'
'Media, Music & Books'
'Musical Instruments'
'Digital Goods'
'Clothing'
'Traditional Clothing'
"Women's Bags"
'Shoes'
'Accessories'
'Lingerie, Sleep & Lounge'
"Girl's Fashion"
'Clothing'
"Men's Bags"
'Shoes'
'Accessories'
"Boy's Fashion"
"Men's Underwear"
"Men's Watches"
"Women's Watches"
'Sunglasses'
'Eyeglasses'
'Women Fashion Jewellery'
'Men Fashion Jewellery'
'Men Shoes & Clothing'
'Women Shoes & Clothing'
'Outdoor Recreation'
'Exercise & Fitness'
'Water Sports'
'Racket Sports'
'Team Sports'
'Travel & Luggage'
'Automotive'
'Motorcycles'
'Auto Care'
'Auto Electronics'
'Moto Parts & Accessories'
'Motorcycle Riding Gear'